# services to run
services:
  # postgres service
  postgres:
    # image of postgres
    image: postgres:13
    # environment variables
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # port config
    ports:
     - 5432:5432
    # add persistency to the container
    volumes:
      - /postgres_data:/var/lib/postgresql/data
